name: tfproviderlint
on: [push, pull_request]

jobs:
  tfproviderlint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Run tfproviderlint
        uses: bflad/tfproviderlint-github-action@master
        with:
          args: -R003=false -R011=false -R012=false -S001=false -S002=false -S003=false -S004=false -S005=false -S006=false -S007=false -S008=false -S009=false -S010=false -S011=false -S012=false -S013=false -S014=false -S015=false -S016=false -S017=false -S018=false -S019=false -S020=false -S021=false -S022=false -S023=false -S024=false -S025=false -S026=false -S027=false -S028=false -S029=false -S030=false -S031=false -S032=false -S033=false -S034=false -S035=false -S036=false -S037=false -AT001=false -AT002=false -AT003=false -AT006=false -AT012=false -R013=false ./cloudflare/
